---
version: '3.4'
services:
  devinfluxdb:
    image: "influxdb:1.8"
    ports:
      - "8086:8086"
    network_mode: bridge
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      start_period: 5s
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=s3cr4t
      - INFLUXDB_ADMIN_PASSWORD=s3cr4t

  devgrafana:
    image: "grafana/grafana:9.5.2"
    ports:
      - "3000:3000"
    network_mode: bridge
    volumes:
      - type: bind
        source: docker-grafana/provisioning
        target: /provisioning
    environment:
      - GF_LOG_MODE=console
      - GF_INSTALL_PLUGINS=simpod-json-datasource
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/provisioning/dashboards/venus-devices.json
      - VGS_INFLUXDB_URL=http://host.docker.internal:8086
      - VGS_INFLUXDB_USERNAME=venusinflux1
      - VGS_INFLUXDB_PASSWORD=venusinflux1
      - VGS_GRAFANA_API_URL=http://host.docker.internal:8088/grafana-api
    depends_on:
      devinfluxdb:
        condition: service_healthy
