---
version: '3.4'
services:

  playground-influxdb:
    image: "influxdb:1.8"
    ports:
      - "8086:8086"
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      start_period: 5s
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER=s3cr4t
      - INFLUXDB_ADMIN_PASSWORD=s3cr4t

  playground-grafana:
    image: "grafana/grafana:9.3.8"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: docker-grafana/provisioning
        target: /provisioning
    environment:
      - GF_LOG_MODE=console
      - GF_INSTALL_PLUGINS=simpod-json-datasource
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/provisioning/dashboards/venus-devices.json
      - VGS_INFLUXDB_URL=http://host.docker.internal:8086
      - VGS_INFLUXDB_USERNAME=s3cr4t
      - VGS_INFLUXDB_PASSWORD=s3cr4t
      - VGS_GRAFANA_API_URL=http://host.docker.internal:8088/grafana-api
    depends_on:
      playground-influxdb:
        condition: service_healthy
      playground-venus-grafana-server:
        condition: service_healthy

  playground-venus-grafana-server:
    image: "venus-grafana-server:playground"
    build:
      context: .
      dockerfile: docker-server/Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - type: bind
        source: ./config
        target: /config
    environment:
      - VGS_INFLUXDB_URL=http://host.docker.internal:8086
      - VGS_INFLUXDB_USERNAME=s3cr4t
      - VGS_INFLUXDB_PASSWORD=s3cr4t
    depends_on:
      playground-influxdb:
        condition: service_healthy

  playground-venus-upnp-browser:
    image: "venus-upnp-browser:playground"
    build:
      context: .
      dockerfile: docker-upnp/Dockerfile
    network_mode: host
    command: ["--discovery-api", "http://host.docker.internal:8088/discovery-api/"]
    depends_on:
      playground-venus-grafana-server:
        condition: service_healthy
